"""
Small-signal AC solver using MNA (Modified Nodal Analysis).
Solves the full circuit at each frequency, computes gain and BW.
Includes ALL transistors + load capacitors.
"""
import numpy as np
from pmos_tft_model import PMOS_TFT

def get_ss_params(W, L, Vs, Vd, Vg):
    """Small-signal parameters at a DC operating point.

    gm/gds are the *terminal* values, extracted by finite-differencing the full
    terminal current get_Idc (which solves the OTFT internal contact nodes).
    The channel gm from _eval_channel is degenerated by the contact resistance;
    Spectre's AC sees the terminal value. Using terminal gm matches Cadence to
    <0.05 dB / <0.1 Hz across the band; channel gm was 0.8 dB / 18 Hz off.
    """
    t = PMOS_TFT(W=W, L=L)
    h = 1e-3
    try:
        Id = lambda vs, vd, vg: t.get_Idc(vs, vd, vg)
        gm  = (Id(Vs, Vd, Vg + h) - Id(Vs, Vd, Vg - h)) / (2 * h)
        gds = (Id(Vs, Vd + h, Vg) - Id(Vs, Vd - h, Vg)) / (2 * h)
        Cgss, Cgdd = t.get_capacitances(Vs, Vd, Vg)
        s1, d1 = t.get_op(Vs, Vd, Vg)
        Ich = t._eval_channel(Vs, Vd, Vg, s1, d1)["Ich"]
        return {"gm": gm, "gds": gds, "Cgs": Cgss, "Cgd": Cgdd, "Ich": Ich}
    except Exception:
        return {"gm": 0, "gds": 1e-12, "Cgs": 0, "Cgd": 0, "Ich": 0}


def ac_solve(sizes, bias, freqs):
    """
    Full small-signal AC analysis.

    sizes: dict of {name: (W, L)}
    bias: dict with VDD, VCM, VB, VC
    freqs: array of frequencies (Hz)

    Returns: gain_vs_freq, bw_Hz, Av_dc_dB
    """
    # ── 1. DC solve to get operating point ──
    from scipy.optimize import fsolve
    VDD = bias["VDD"]; VCM = bias["VCM"]; VB = bias["VB"]; VC = bias["VC"]
    gmin = 1e-12

    def Id(name, Vs, Vd, Vg):
        W, L = sizes[name]
        t = PMOS_TFT(W=W, L=L)
        try: return abs(t.get_Idc(Vs, Vd, Vg))
        except: return 1e-18

    def residuals(x):
        n2, VOP, VON, vfbp, vfbn, n20 = x
        VIP = VIN = VCM
        return [
            Id("M6", VDD, n2, VB) - Id("M7", n2, VOP, VIP) - Id("M8", n2, VON, VIN) - n2*gmin,
            Id("M7", n2, VOP, VIP) - Id("M9", VOP, 0.0, vfbp) - VOP*gmin,
            Id("M8", n2, VON, VIN) - Id("M10", VON, 0.0, vfbn) - VON*gmin,
            Id("M13", n20, vfbp, VON) - Id("M15", vfbp, 0.0, 0.0) - vfbp*gmin,
            Id("M12", n20, vfbn, VOP) - Id("M14", vfbn, 0.0, 0.0) - vfbn*gmin,
            Id("M11", VDD, n20, VC) - Id("M12", n20, vfbn, VOP) - Id("M13", n20, vfbp, VON) - n20*gmin,
        ]

    for trial in range(5):
        x0 = [VCM+7+trial, VCM-4, VCM-4, VCM-8, VCM-8, VCM+15]
        try:
            sol, _, ier, _ = fsolve(residuals, x0, full_output=True, xtol=1e-12, maxfev=3000)
            if ier == 1: break
        except: pass
    else:
        return None  # DC didn't converge

    n2_dc, VOP_dc, _, vfb_dc, _, n20_dc = sol

    # ── 2. Get small-signal parameters at DC op ──
    ss = {}

    # M7: s=net2, d=VOP, g=VIP=VCM
    ss["M7"] = get_ss_params(sizes["M7"][0], sizes["M7"][1], n2_dc, VOP_dc, VCM)
    # M8: s=net2, d=VON, g=VIN=VCM
    ss["M8"] = get_ss_params(sizes["M8"][0], sizes["M8"][1], n2_dc, VOP_dc, VCM)  # symmetric
    # M9: s=VOP, d=GND, g=vfb
    ss["M9"] = get_ss_params(sizes["M9"][0], sizes["M9"][1], VOP_dc, 0.0, vfb_dc)
    # M10: symmetric
    ss["M10"] = get_ss_params(sizes["M10"][0], sizes["M10"][1], VOP_dc, 0.0, vfb_dc)
    # M12: s=net20, d=vfbn, g=VOP
    ss["M12"] = get_ss_params(sizes["M12"][0], sizes["M12"][1], n20_dc, vfb_dc, VOP_dc)
    # M13: s=net20, d=vfbp, g=VON — symmetric with M12
    ss["M13"] = get_ss_params(sizes["M13"][0], sizes["M13"][1], n20_dc, vfb_dc, VOP_dc)
    # M14: s=vfbn, d=GND, g=GND
    ss["M14"] = get_ss_params(sizes["M14"][0], sizes["M14"][1], vfb_dc, 0.0, 0.0)
    # M15: symmetric
    ss["M15"] = get_ss_params(sizes["M15"][0], sizes["M15"][1], vfb_dc, 0.0, 0.0)
    # M6: s=VDD, d=net2, g=VB — net2 is AC ground
    ss["M6"] = get_ss_params(sizes["M6"][0], sizes["M6"][1], VDD, n2_dc, VB)
    # M11: s=VDD, d=net20, g=VC — VDD is AC ground
    ss["M11"] = get_ss_params(sizes["M11"][0], sizes["M11"][1], VDD, n20_dc, VC)

    # ── 3. Build & solve the full 6-node small-signal MNA ──
    # Full differential circuit, no half-circuit approximation: net2 and net20
    # are real solved nodes (they fall out to AC zero by symmetry). One uniform
    # transistor stamp (ac_mna._stamp_mos) is applied to all 10 devices.
    # Node indices: VOP=0, VON=1, vfbp=2, vfbn=3, net20=4, net2=5
    from ac_mna import _stamp_mos, _stamp_adm
    VOP, VON, VFBP, VFBN, NET20, NET2 = 0, 1, 2, 3, 4, 5
    NN = 6
    GND = ("v", 0.0)   # AC ground
    VDDg = ("v", 0.0)  # ideal supply -> AC ground
    n = lambda i: ("n", i)

    CL = 5e-12         # load capacitance per output
    vin_diff = 1.0
    half = vin_diff / 2.0
    VIP = ("v", +half); VIN = ("v", -half)

    # gates of M6/M11 are DC bias sources -> AC ground
    # device: (name, drain, gate, source)
    devs = [
        ("M6",  n(NET2),  GND, VDDg),
        ("M7",  n(VOP),   VIP, n(NET2)),
        ("M8",  n(VON),   VIN, n(NET2)),
        ("M9",  GND,      n(VFBP), n(VOP)),
        ("M10", GND,      n(VFBN), n(VON)),
        ("M11", n(NET20), GND, VDDg),
        ("M12", n(VFBN),  n(VOP), n(NET20)),
        ("M13", n(VFBP),  n(VON), n(NET20)),
        ("M14", GND,      GND, n(VFBN)),
        ("M15", GND,      GND, n(VFBP)),
    ]

    gains = []
    for f in freqs:
        jw = 2j * np.pi * f
        Y = np.zeros((NN, NN), dtype=complex)
        RHS = np.zeros(NN, dtype=complex)
        for name, d, g, s in devs:
            p = ss[name]
            _stamp_mos(Y, RHS, d, g, s, p["gm"], p["gds"], p["Cgs"], p["Cgd"], jw)
        _stamp_adm(Y, RHS, n(VOP), GND, jw * CL)
        _stamp_adm(Y, RHS, n(VON), GND, jw * CL)
        V = np.linalg.solve(Y, RHS)
        gains.append(abs(V[VOP] - V[VON]) / vin_diff)

    gains = np.array(gains)
    Av_dc = gains[0]
    Av_dc_dB = 20 * np.log10(max(Av_dc, 1e-9))

    # upper -3dB: first freq above the peak where gain drops below peak/sqrt(2)
    peak = gains.max()
    a3 = peak / np.sqrt(2)
    ipk = int(np.argmax(gains))
    bw_Hz = freqs[-1]
    for i in range(ipk, len(gains)):
        if gains[i] < a3:
            bw_Hz = freqs[i]; break

    return {
        "Av_dc_dB": Av_dc_dB,
        "peak_dB": 20 * np.log10(peak),
        "bw_Hz": bw_Hz,
        "gains": gains,
        "freqs": freqs,
        "dc_op": {"net2": n2_dc, "VOP": VOP_dc, "vfb": vfb_dc, "n20": n20_dc},
        "ss": ss,
    }


# ── Test with best design from sweep ──
if __name__ == "__main__":
    sizes = {
        "M6": (3000, 150), "M7": (25000, 150), "M8": (25000, 150),
        "M9": (12000, 500), "M10": (12000, 500),
        "M11": (300, 100), "M12": (500, 80), "M13": (500, 80),
        "M14": (2000, 500), "M15": (2000, 500),
    }
    bias = {"VDD": 40.0, "VCM": 32.0, "VB": 20.0, "VC": 26.0}

    freqs = np.logspace(-2, 4, 400)  # 0.01 Hz to 10 kHz

    print("Running AC analysis...")
    result = ac_solve(sizes, bias, freqs)

    if result:
        print(f"DC gain: {result['Av_dc_dB']:.1f} dB   peak: {result['peak_dB']:.1f} dB  (Cadence 19.96 dB)")
        print(f"-3dB BW: {result['bw_Hz']:.1f} Hz  (Cadence 52.3 Hz)")
        print(f"DC op: net2={result['dc_op']['net2']:.1f}V VOP={result['dc_op']['VOP']:.1f}V vfb={result['dc_op']['vfb']:.1f}V")
        print(f"")
        for name in ["M7","M9","M12","M14"]:
            s = result["ss"][name]
            print(f"{name}: gm={s['gm']*1e9:.0f}nS gds={s['gds']*1e9:.2f}nS Cgs={s['Cgs']*1e12:.1f}pF Cgd={s['Cgd']*1e12:.1f}pF")
    else:
        print("DC did not converge")
