"""
Small-signal AC solver using MNA (Modified Nodal Analysis).
Solves the full circuit at each frequency, computes gain and BW.
Includes ALL transistors + load capacitors.
"""
import numpy as np
from pmos_tft_model import PMOS_TFT
from topology import AFE_TOPO


def _dev_corner(corner, name):
    """Resolve the model-shift dict for one device.

    corner may be:
      - None / {}                              -> nominal (no shift)
      - flat dict {'pvt0':.., 'pbeta0':..}     -> GLOBAL shift, same for all devices
                                                  (process corner)
      - per-device map {'M7':{...}, 'M8':{...}}-> PER-DEVICE shift (mismatch:
                                                  each device its own mvt0/mbeta0)
    """
    if not corner:
        return {}
    if any(isinstance(v, dict) for v in corner.values()):     # per-device map
        return corner.get(name, {})
    return corner                                             # global shift


def _symmetric_seed(sizes, bias, Id, gmin, seeds=None):
    """AFE-specific symmetric DC solve (matched halves: VON=VOP, VFBN=VFBP). 4 unknowns
    [net2, vop, vfb, net20]. Used as a POST-PROCESS guard: when the full 6-node solve
    latches to a symmetry-broken root (cross-coupled positive feedback) in a no-mismatch
    case, re-solving this symmetric system — seeded from the symmetrized average of the
    latched solution — recovers the physical symmetric branch that Spectre finds.
    Returns a {node:V} dict, or None."""
    from scipy.optimize import fsolve
    VDD, VCM, VB, VC = bias["VDD"], bias["VCM"], bias["VB"], bias["VC"]

    def f(u):
        net2, vop, vfb, net20 = u
        return [
            Id("M6", VDD, net2, VB) - 2 * Id("M7", net2, vop, VCM) - net2 * gmin,
            Id("M7", net2, vop, VCM) - Id("M9", vop, 0.0, vfb) - vop * gmin,
            Id("M13", net20, vfb, vop) - Id("M15", vfb, 0.0, 0.0) - vfb * gmin,
            Id("M11", VDD, net20, VC) - 2 * Id("M12", net20, vfb, vop) - net20 * gmin,
        ]
    trials = list(seeds or []) + [[VCM + 7, VCM - 4, VCM - 8, VCM + 15],
                                  [VCM + 9, VCM - 2, VCM - 10, VCM + 12],
                                  [VCM + 5, VCM - 6, VCM - 6, VCM + 18]]
    for u0 in trials:
        try:
            sol, _, ier, _ = fsolve(f, u0, full_output=True, xtol=1e-12, maxfev=4000)
            if ier == 1:
                n2, vop, vfb, n20 = sol
                return {"VOP": vop, "VON": vop, "VFBP": vfb, "VFBN": vfb,
                        "NET20": n20, "NET2": n2}
        except Exception:
            pass
    return None


def _symmetric_continuation(sizes, bias, Id, gmin):
    """AFE symmetric DC via SOURCE-RAMP continuation (power-up homotopy): scale all
    rails 0->1 and track the solution from the powered-down state. This follows the
    same physical branch Spectre's pseudo-transient/gmin-stepping converges to, so it
    selects the correct equilibrium even when the symmetric circuit is multistable
    (a 'normal-on' branch vs a degenerate near-off branch). 4 unknowns: net2,vop,vfb,net20.
    Returns a symmetric {node:V} dict (used as the PRIMARY DC seed), or None."""
    from scipy.optimize import fsolve
    VDD, VCM, VB, VC = bias["VDD"], bias["VCM"], bias["VB"], bias["VC"]

    def f(u, sc):
        net2, vop, vfb, net20 = u
        Vdd, Vcm, Vb, Vc = VDD * sc, VCM * sc, VB * sc, VC * sc
        return [
            Id("M6", Vdd, net2, Vb) - 2 * Id("M7", net2, vop, Vcm) - net2 * gmin,
            Id("M7", net2, vop, Vcm) - Id("M9", vop, 0.0, vfb) - vop * gmin,
            Id("M13", net20, vfb, vop) - Id("M15", vfb, 0.0, 0.0) - vfb * gmin,
            Id("M11", Vdd, net20, Vc) - 2 * Id("M12", net20, vfb, vop) - net20 * gmin,
        ]
    u = np.array([VCM, VCM, VCM, VCM]) * 0.1          # near powered-down
    for sc in np.linspace(0.1, 1.0, 19):
        ok = False
        for seed in (u, np.array([VCM+7, VCM-4, VCM-8, VCM+15]) * sc):
            try:
                s, _, ier, _ = fsolve(lambda z: f(z, sc), seed,
                                      full_output=True, xtol=1e-12, maxfev=4000)
                if ier == 1:
                    u = s; ok = True; break
            except Exception:
                pass
        if not ok:
            return None
    n2, vop, vfb, n20 = u
    return {"VOP": vop, "VON": vop, "VFBP": vfb, "VFBN": vfb, "NET20": n20, "NET2": n2}


def get_ss_params(W, L, Vs, Vd, Vg, corner=None):
    """Small-signal parameters at a DC operating point.

    gm/gds are the *terminal* values, extracted by finite-differencing the full
    terminal current get_Idc (which solves the OTFT internal contact nodes).
    The channel gm from _eval_channel is degenerated by the contact resistance;
    Spectre's AC sees the terminal value. Using terminal gm matches Cadence to
    <0.05 dB / <0.1 Hz across the band; channel gm was 0.8 dB / 18 Hz off.

    corner: optional dict of model process shifts, e.g. {'pvt0':.., 'pbeta0':..}.
    """
    t = PMOS_TFT(W=W, L=L, **(corner or {}))
    h = 1e-3
    try:
        Id = lambda vs, vd, vg: t.get_Idc(vs, vd, vg)
        gm  = (Id(Vs, Vd, Vg + h) - Id(Vs, Vd, Vg - h)) / (2 * h)
        gds = (Id(Vs, Vd + h, Vg) - Id(Vs, Vd - h, Vg)) / (2 * h)
        Cgss, Cgdd = t.get_capacitances(Vs, Vd, Vg)
        s1, d1 = t.get_op(Vs, Vd, Vg)
        Ich = t._eval_channel(Vs, Vd, Vg, s1, d1)["Ich"]
        return {"gm": gm, "gds": gds, "Cgs": Cgss, "Cgd": Cgdd, "Ich": Ich}
    except Exception:
        return {"gm": 0, "gds": 1e-12, "Cgs": 0, "Cgd": 0, "Ich": 0}


def ac_solve(sizes, bias, freqs, corner=None, x0_guess=None, topo=AFE_TOPO):
    """
    Full small-signal AC analysis — topology supplied by `topo` (default AFE_TOPO).

    sizes: dict of {name: (W, L)}
    bias: dict with VDD, VCM, VB, VC
    freqs: array of frequencies (Hz)
    corner: process shifts — flat dict (global) or per-device map (mismatch); see _dev_corner.
    x0_guess: optional DC seed, either a {node: V} dict (e.g. a prior dc_op) or a vector.

    DC KCL, per-device bias mapping, and the AC terminal list are all DERIVED from
    `topo` (see topology.py) — no hand-written per-device wiring here.
    """
    from scipy.optimize import fsolve
    VCM = bias["VCM"]
    VDD = bias["VDD"]
    gmin = 1e-12

    def Id(name, Vs, Vd, Vg):
        W, L = sizes[name]
        try:
            return abs(PMOS_TFT(W=W, L=L, **_dev_corner(corner, name)).get_Idc(Vs, Vd, Vg))
        except Exception:
            return 1e-18

    # ── 1. DC solve (residuals built from the topology) ──
    residuals = lambda x: topo.dc_residuals(x, bias, Id, gmin)
    guesses = []
    if x0_guess is not None:
        # A seed was supplied (e.g. an MC/corner sweep seeded from the nominal op that
        # was itself found by continuation): trust it — it already encodes the right
        # branch — and SKIP the (expensive) continuation. Keeps in-loop sweeps fast.
        guesses.append(topo.guess_vector(x0_guess, default=VCM)
                       if isinstance(x0_guess, dict) else list(x0_guess))
    else:
        # Cold solve: run source-ramp continuation on the symmetric system to land on
        # the physical power-up branch Spectre picks (handles symmetry-broken AND
        # degenerate multistable points). Tried first.
        cont = _symmetric_continuation(sizes, bias, Id, gmin)
        if cont is not None:
            guesses.append(topo.guess_vector(cont))
    base = {"VOP": VCM-4, "VON": VCM-4, "VFBP": VCM-8, "VFBN": VCM-8, "NET20": VCM+15, "NET2": VCM+7}
    for t in range(5):
        g = dict(base); g["NET2"] = VCM + 7 + t
        guesses.append(topo.guess_vector(g))
    guesses.append(topo.guess_vector({"VOP": VCM-2, "VON": VCM-2, "VFBP": VCM-10,
                                       "VFBN": VCM-10, "NET20": VCM+12, "NET2": VCM+9}))
    guesses.append(topo.guess_vector({"VOP": VCM-6, "VON": VCM-6, "VFBP": VCM-6,
                                       "VFBN": VCM-6, "NET20": VCM+18, "NET2": VCM+5}))
    for x0 in guesses:
        try:
            sol, _, ier, _ = fsolve(residuals, x0, full_output=True, xtol=1e-12, maxfev=3000)
            if ier == 1:
                break
        except Exception:
            pass
    else:
        # ── FALLBACK (runs ONLY when every standard guess failed; never alters
        # already-converged points). Goal: pick the SAME physical branch Spectre
        # picks, even for multistable points. ──
        VDD = bias["VDD"]
        base_g = topo.guess_vector({"VOP": VCM-4, "VON": VCM-4, "VFBP": VCM-8,
                                    "VFBN": VCM-8, "NET20": VCM+15, "NET2": VCM+7})

        def _solve(bias_d, gm, x0):
            try:
                s, _, ier, _ = fsolve(lambda z: topo.dc_residuals(z, bias_d, Id, gm),
                                      x0, full_output=True, xtol=1e-12, maxfev=4000)
                return s if ier == 1 else None
            except Exception:
                return None

        sol = None
        # (a) SOURCE-RAMP continuation: scale all rails 0->1, tracking the power-up
        #     trajectory. This follows the physical (Spectre) branch through
        #     multistable regions instead of jumping to an alternate equilibrium.
        x = np.array(base_g) * 0.2
        ramp_ok = True
        for lam in np.linspace(0.2, 1.0, 17):
            bl = {k: v * lam for k, v in bias.items()}
            s = _solve(bl, gmin, x)
            if s is None:
                s = _solve(bl, gmin, np.array(base_g) * lam)   # re-seed at this step
            if s is None:
                ramp_ok = False; break
            x = s
        if ramp_ok:
            sol = x
        # (b) gmin-stepping backup if the ramp couldn't track all the way
        if sol is None:
            flat = topo.guess_vector({n: VCM for n in topo.solved})
            for x0 in guesses + [flat]:
                xc = list(np.clip(x0, 0.1, VDD - 0.1))
                good = True
                for gm in (1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12):
                    s = _solve(bias, gm, xc)
                    if s is None:
                        good = False; break
                    xc = list(s)
                if good:
                    sol = xc; break
        if sol is None:
            return None  # DC didn't converge even with continuation

    nv = topo.node_vals(sol)                      # {node_name: voltage}, full asymmetric op
    per_dev = bool(corner) and any(isinstance(v, dict) for v in corner.values())

    # ── PHYSICALITY GUARD ── No internal node can sit above the supply or below ground
    # here. A solution with e.g. net20 > VDD means the tail M11 is reversed — a
    # non-physical alternate branch Spectre never picks. Re-solve seeded strictly inside
    # the rails and prefer an in-box solution. (Validated designs are already in-box, so
    # this never fires for them.)
    def _inbox(d):
        return all(-0.5 <= v <= VDD + 0.5 for v in d.values())
    if not _inbox(nv):
        for g in ({"VOP": VDD*0.6, "VON": VDD*0.6, "VFBP": VDD*0.4, "VFBN": VDD*0.4,
                   "NET20": VDD-4, "NET2": min(VCM+7, VDD-2)},
                  {"VOP": VDD*0.5, "VON": VDD*0.5, "VFBP": VDD*0.3, "VFBN": VDD*0.3,
                   "NET20": VDD-3, "NET2": VDD-5}):
            try:
                s2, _, ier, _ = fsolve(residuals, topo.guess_vector(g),
                                       full_output=True, xtol=1e-12, maxfev=4000)
            except Exception:
                continue
            if ier == 1 and _inbox(topo.node_vals(s2)):
                nv = topo.node_vals(s2); break

    # ── SYMMETRY GUARD ── No per-device mismatch ⇒ physical op is symmetric (VOP=VON,
    # VFBP=VFBN). If fsolve latched to a symmetry-broken root, re-solve the symmetric
    # system seeded from the symmetrized average (right next to the physical root).
    # Only fires on no-mismatch + clearly-asymmetric, so symmetric (validated) points
    # are untouched.
    if (not per_dev) and (abs(nv["VOP"] - nv["VON"]) > 1e-2 or
                          abs(nv["VFBP"] - nv["VFBN"]) > 1e-2):
        avg = [nv["NET2"], 0.5 * (nv["VOP"] + nv["VON"]),
               0.5 * (nv["VFBP"] + nv["VFBN"]), nv["NET20"]]
        symv = _symmetric_seed(sizes, bias, Id, gmin, seeds=[avg])
        if symv is not None:
            nv = symv                             # physical symmetric branch (Spectre-matching)

    bpts = topo.bias_points(nv, bias)             # per-device (Vs, Vd, Vg)

    # ── 2. Small-signal params at the true per-device DC op ──
    ss = {name: get_ss_params(sizes[name][0], sizes[name][1], *bpts[name],
                              corner=_dev_corner(corner, name))
          for name, *_ in topo.devices}

    # ── 3. Build & solve the small-signal MNA (terminals from the topology) ──
    from ac_mna import _stamp_mos, _stamp_adm
    iVOP, iVON = topo.idx["VOP"], topo.idx["VON"]
    NN = topo.n
    GND = ("v", 0.0)
    CL = 5e-12
    vin_diff = 1.0
    half = vin_diff / 2.0
    devs = topo.ac_devices(drive={"M7": +half, "M8": -half})   # differential input on the pair

    gains = []
    for f in freqs:
        jw = 2j * np.pi * f
        Y = np.zeros((NN, NN), dtype=complex)
        RHS = np.zeros(NN, dtype=complex)
        for name, d, g, s in devs:
            p = ss[name]
            _stamp_mos(Y, RHS, d, g, s, p["gm"], p["gds"], p["Cgs"], p["Cgd"], jw)
        _stamp_adm(Y, RHS, ("n", iVOP), GND, jw * CL)
        _stamp_adm(Y, RHS, ("n", iVON), GND, jw * CL)
        V = np.linalg.solve(Y, RHS)
        gains.append(abs(V[iVOP] - V[iVON]) / vin_diff)

    gains = np.array(gains)
    Av_dc = gains[0]
    Av_dc_dB = 20 * np.log10(max(Av_dc, 1e-9))
    peak = gains.max()
    a3 = peak / np.sqrt(2)
    ipk = int(np.argmax(gains))
    bw_Hz = freqs[-1]
    for i in range(ipk, len(gains)):
        if gains[i] < a3:
            bw_Hz = freqs[i]; break

    # dc_op: topology names + legacy aliases (net2/n20/vfb) for existing consumers
    dc_op = {**nv, "net2": nv["NET2"], "n20": nv["NET20"],
             "vfb": nv["VFBP"], "vfbp": nv["VFBP"], "vfbn": nv["VFBN"]}
    return {
        "Av_dc_dB": Av_dc_dB,
        "peak_dB": 20 * np.log10(peak),
        "bw_Hz": bw_Hz,
        "gains": gains,
        "freqs": freqs,
        "dc_op": dc_op,
        "ss": ss,
    }


# ── Test with best design from sweep ──
if __name__ == "__main__":
    sizes = {
        "M6": (3000, 150), "M7": (25000, 150), "M8": (25000, 150),
        "M9": (12000, 500), "M10": (12000, 500),
        "M11": (300, 100), "M12": (500, 80), "M13": (500, 80),
        "M14": (2000, 500), "M15": (2000, 500),
    }
    bias = {"VDD": 40.0, "VCM": 32.0, "VB": 20.0, "VC": 26.0}

    freqs = np.logspace(-2, 4, 400)  # 0.01 Hz to 10 kHz

    print("Running AC analysis...")
    result = ac_solve(sizes, bias, freqs)

    if result:
        print(f"DC gain: {result['Av_dc_dB']:.1f} dB   peak: {result['peak_dB']:.1f} dB  (Cadence 19.96 dB)")
        print(f"-3dB BW: {result['bw_Hz']:.1f} Hz  (Cadence 52.3 Hz)")
        print(f"DC op: net2={result['dc_op']['net2']:.1f}V VOP={result['dc_op']['VOP']:.1f}V vfb={result['dc_op']['vfb']:.1f}V")
        print(f"")
        for name in ["M7","M9","M12","M14"]:
            s = result["ss"][name]
            print(f"{name}: gm={s['gm']*1e9:.0f}nS gds={s['gds']*1e9:.2f}nS Cgs={s['Cgs']*1e12:.1f}pF Cgd={s['Cgd']*1e12:.1f}pF")
    else:
        print("DC did not converge")
