"""
Small-signal AC solver using MNA (Modified Nodal Analysis).
Solves the full circuit at each frequency, computes gain and BW.
Includes ALL transistors + load capacitors.
"""
import numpy as np
from pmos_tft_model import PMOS_TFT
from topology import AFE_TOPO


def _dev_corner(corner, name):
    """Resolve the model-shift dict for one device.

    corner may be:
      - None / {}                              -> nominal (no shift)
      - flat dict {'pvt0':.., 'pbeta0':..}     -> GLOBAL shift, same for all devices
                                                  (process corner)
      - per-device map {'M7':{...}, 'M8':{...}}-> PER-DEVICE shift (mismatch:
                                                  each device its own mvt0/mbeta0)
    """
    if not corner:
        return {}
    if any(isinstance(v, dict) for v in corner.values()):     # per-device map
        return corner.get(name, {})
    return corner                                             # global shift


def get_ss_params(W, L, Vs, Vd, Vg, corner=None):
    """Small-signal parameters at a DC operating point.

    gm/gds are the *terminal* values, extracted by finite-differencing the full
    terminal current get_Idc (which solves the OTFT internal contact nodes).
    The channel gm from _eval_channel is degenerated by the contact resistance;
    Spectre's AC sees the terminal value. Using terminal gm matches Cadence to
    <0.05 dB / <0.1 Hz across the band; channel gm was 0.8 dB / 18 Hz off.

    corner: optional dict of model process shifts, e.g. {'pvt0':.., 'pbeta0':..}.
    """
    t = PMOS_TFT(W=W, L=L, **(corner or {}))
    h = 1e-3
    try:
        Id = lambda vs, vd, vg: t.get_Idc(vs, vd, vg)
        gm  = (Id(Vs, Vd, Vg + h) - Id(Vs, Vd, Vg - h)) / (2 * h)
        gds = (Id(Vs, Vd + h, Vg) - Id(Vs, Vd - h, Vg)) / (2 * h)
        Cgss, Cgdd = t.get_capacitances(Vs, Vd, Vg)
        s1, d1 = t.get_op(Vs, Vd, Vg)
        Ich = t._eval_channel(Vs, Vd, Vg, s1, d1)["Ich"]
        return {"gm": gm, "gds": gds, "Cgs": Cgss, "Cgd": Cgdd, "Ich": Ich}
    except Exception:
        return {"gm": 0, "gds": 1e-12, "Cgs": 0, "Cgd": 0, "Ich": 0}


def ac_solve(sizes, bias, freqs, corner=None, x0_guess=None, topo=AFE_TOPO):
    """
    Full small-signal AC analysis — topology supplied by `topo` (default AFE_TOPO).

    sizes: dict of {name: (W, L)}
    bias: dict with VDD, VCM, VB, VC
    freqs: array of frequencies (Hz)
    corner: process shifts — flat dict (global) or per-device map (mismatch); see _dev_corner.
    x0_guess: optional DC seed, either a {node: V} dict (e.g. a prior dc_op) or a vector.

    DC KCL, per-device bias mapping, and the AC terminal list are all DERIVED from
    `topo` (see topology.py) — no hand-written per-device wiring here.
    """
    from scipy.optimize import fsolve
    VCM = bias["VCM"]
    gmin = 1e-12

    def Id(name, Vs, Vd, Vg):
        W, L = sizes[name]
        try:
            return abs(PMOS_TFT(W=W, L=L, **_dev_corner(corner, name)).get_Idc(Vs, Vd, Vg))
        except Exception:
            return 1e-18

    # ── 1. DC solve (residuals built from the topology) ──
    residuals = lambda x: topo.dc_residuals(x, bias, Id, gmin)
    guesses = []
    if x0_guess is not None:
        guesses.append(topo.guess_vector(x0_guess, default=VCM)
                       if isinstance(x0_guess, dict) else list(x0_guess))
    base = {"VOP": VCM-4, "VON": VCM-4, "VFBP": VCM-8, "VFBN": VCM-8, "NET20": VCM+15, "NET2": VCM+7}
    for t in range(5):
        g = dict(base); g["NET2"] = VCM + 7 + t
        guesses.append(topo.guess_vector(g))
    guesses.append(topo.guess_vector({"VOP": VCM-2, "VON": VCM-2, "VFBP": VCM-10,
                                       "VFBN": VCM-10, "NET20": VCM+12, "NET2": VCM+9}))
    guesses.append(topo.guess_vector({"VOP": VCM-6, "VON": VCM-6, "VFBP": VCM-6,
                                       "VFBN": VCM-6, "NET20": VCM+18, "NET2": VCM+5}))
    for x0 in guesses:
        try:
            sol, _, ier, _ = fsolve(residuals, x0, full_output=True, xtol=1e-12, maxfev=3000)
            if ier == 1:
                break
        except Exception:
            pass
    else:
        return None  # DC didn't converge

    nv = topo.node_vals(sol)                      # {node_name: voltage}, full asymmetric op
    bpts = topo.bias_points(nv, bias)             # per-device (Vs, Vd, Vg)

    # ── 2. Small-signal params at the true per-device DC op ──
    ss = {name: get_ss_params(sizes[name][0], sizes[name][1], *bpts[name],
                              corner=_dev_corner(corner, name))
          for name, *_ in topo.devices}

    # ── 3. Build & solve the small-signal MNA (terminals from the topology) ──
    from ac_mna import _stamp_mos, _stamp_adm
    iVOP, iVON = topo.idx["VOP"], topo.idx["VON"]
    NN = topo.n
    GND = ("v", 0.0)
    CL = 5e-12
    vin_diff = 1.0
    half = vin_diff / 2.0
    devs = topo.ac_devices(drive={"M7": +half, "M8": -half})   # differential input on the pair

    gains = []
    for f in freqs:
        jw = 2j * np.pi * f
        Y = np.zeros((NN, NN), dtype=complex)
        RHS = np.zeros(NN, dtype=complex)
        for name, d, g, s in devs:
            p = ss[name]
            _stamp_mos(Y, RHS, d, g, s, p["gm"], p["gds"], p["Cgs"], p["Cgd"], jw)
        _stamp_adm(Y, RHS, ("n", iVOP), GND, jw * CL)
        _stamp_adm(Y, RHS, ("n", iVON), GND, jw * CL)
        V = np.linalg.solve(Y, RHS)
        gains.append(abs(V[iVOP] - V[iVON]) / vin_diff)

    gains = np.array(gains)
    Av_dc = gains[0]
    Av_dc_dB = 20 * np.log10(max(Av_dc, 1e-9))
    peak = gains.max()
    a3 = peak / np.sqrt(2)
    ipk = int(np.argmax(gains))
    bw_Hz = freqs[-1]
    for i in range(ipk, len(gains)):
        if gains[i] < a3:
            bw_Hz = freqs[i]; break

    # dc_op: topology names + legacy aliases (net2/n20/vfb) for existing consumers
    dc_op = {**nv, "net2": nv["NET2"], "n20": nv["NET20"],
             "vfb": nv["VFBP"], "vfbp": nv["VFBP"], "vfbn": nv["VFBN"]}
    return {
        "Av_dc_dB": Av_dc_dB,
        "peak_dB": 20 * np.log10(peak),
        "bw_Hz": bw_Hz,
        "gains": gains,
        "freqs": freqs,
        "dc_op": dc_op,
        "ss": ss,
    }


# ── Test with best design from sweep ──
if __name__ == "__main__":
    sizes = {
        "M6": (3000, 150), "M7": (25000, 150), "M8": (25000, 150),
        "M9": (12000, 500), "M10": (12000, 500),
        "M11": (300, 100), "M12": (500, 80), "M13": (500, 80),
        "M14": (2000, 500), "M15": (2000, 500),
    }
    bias = {"VDD": 40.0, "VCM": 32.0, "VB": 20.0, "VC": 26.0}

    freqs = np.logspace(-2, 4, 400)  # 0.01 Hz to 10 kHz

    print("Running AC analysis...")
    result = ac_solve(sizes, bias, freqs)

    if result:
        print(f"DC gain: {result['Av_dc_dB']:.1f} dB   peak: {result['peak_dB']:.1f} dB  (Cadence 19.96 dB)")
        print(f"-3dB BW: {result['bw_Hz']:.1f} Hz  (Cadence 52.3 Hz)")
        print(f"DC op: net2={result['dc_op']['net2']:.1f}V VOP={result['dc_op']['VOP']:.1f}V vfb={result['dc_op']['vfb']:.1f}V")
        print(f"")
        for name in ["M7","M9","M12","M14"]:
            s = result["ss"][name]
            print(f"{name}: gm={s['gm']*1e9:.0f}nS gds={s['gds']*1e9:.2f}nS Cgs={s['Cgs']*1e12:.1f}pF Cgd={s['Cgd']*1e12:.1f}pF")
    else:
        print("DC did not converge")
